version: "3"

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    expose:
      - "8080"

  db:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"