version: '3.8'
services:
  devcontainer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../products:/var/www/html
    ports:
      - '8080:80'
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ../products:/var/www/html